### PR TITLE
sec supports embedded

### PR DESCRIPTION
**Pull request by JcDai**

### CODE REVIEW

**Review by mtao — COMMENTED** [review]
if this is complete this seems reasonable to me.
where did this break?

**Review by mtao — COMMENTED** [review]
Was that one change all that was necessary to get sec working on embedded? Do you still want this pr?

**Comment by JcDai** [comment]
> Was that one change all that was necessary to get sec working on embedded? Do you still want this pr?

yes this pr is needed. I think it's finished and can be merged

**Review by mtao — APPROVED** [review]
lgtm

**Pull request merged**
